server:
    port: 8080
    servlet:
        context-path: /pfg-datasharing
spring:
    datasource:
        database: pdspdb
        db-schema: pdsp
        host: test
        password: sa
        port: 5432
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        username: sa
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
        show-sql: true
web:
    cors:
        allowedOrigins: https://*.moodys.com,https://moodys.com
