logging:
    file: logs/app.log
    level:
        com:
            moodys:
                mis:
                    pfg:
                        dsp: DEBUG
        org:
            springframework: ERROR
    pattern:
        console: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'
        file: '%d %p %c{1.} [%t] %m%n'
server:
    port: 8080
    servlet:
        context-path: /pfg-datasharing
spring:
    datasource:
        database: pdspdb
        db-schema: pdsp
        host: test
        password: sa
        port: 5432
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        username: sa
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
        show-sql: true
web:
    cors:
        allowedOrigins: https://*.moodys.com,https://moodys.com
